---
# tasks file for webserver
    - name: Apache install
      yum:
        name: "{{ packages }}"
        state: present
      notify: 
        - httpd_restarted

    - name: create index file and copy
      shell: "echo $HOSTNAME > index.html && cp index.html /var/www/html/index.html"
      notify: 
        - httpd_restarted

    - name: add permission
      file:
        path: /var/www/html/index.html
        state: file
        mode: '0444'
      notify: 
        - httpd_restarted
    
    

